-- Table: itembarcode
CREATE TABLE IF NOT EXISTS itembarcode (
    itembarcode_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    itembarcode_isdisabled BOOLEAN DEFAULT FALSE NOT NULL,

    item_id BIGINT NOT NULL,
    barcode VARCHAR(50) NOT NULL,
    brand_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    datatimestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_itembarcode PRIMARY KEY (itembarcode_id),
    CONSTRAINT uk_itembarcode UNIQUE (brand_id, barcode),
    CONSTRAINT fk_itembarcode_item_id FOREIGN KEY (item_id) REFERENCES item (item_id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_itembarcode_item_id ON itembarcode (item_id);
CREATE INDEX IF NOT EXISTS idx_itembarcode_barcode ON itembarcode (barcode);
CREATE INDEX IF NOT EXISTS idx_itembarcode_datatimestamp ON itembarcode (datatimestamp);
