-- Table: item
CREATE TABLE IF NOT EXISTS item (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    item_art VARCHAR(100) NOT NULL,
    item_col VARCHAR(50),
    item_size VARCHAR(10),
    item_descr VARCHAR(255),
    item_pricegross DECIMAL(15,2) DEFAULT 0.00 NOT NULL,
    item_price DECIMAL(15,2) DEFAULT 0.00 NOT NULL,
    item_disc DECIMAL(15,2) DEFAULT 0.00 NOT NULL,
    item_isspecialprice BOOLEAN DEFAULT FALSE NOT NULL,
    item_isdisabled BOOLEAN DEFAULT FALSE NOT NULL,
    ctg_id INTEGER,
    ctg_name VARCHAR(255),
    unit_id INTEGER,
    unit_name VARCHAR(255),
    struct_id INTEGER,
    struct_name VARCHAR(255),
    brand_id INTEGER,
    brand_name VARCHAR(255),
    datatimestamp TIMESTAMP NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (item_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_item_art ON item (item_art);
CREATE INDEX IF NOT EXISTS idx_item_datatimestamp ON item (datatimestamp);